services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/Maksimplyt/n8n
    branch: master
    region: frankfurt
    plan: free
    dockerfilePath: docker/images/n8n/Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        fromEnvVar: N8N_PASSWORD
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_URL
        value: https://n8n.maksimbot.com/
